# Generated by Django 2.1.7 on 2019-04-04 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('D', 'In Delivery'), ('C', 'Completed')], default='P', max_length=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('toppings_number', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='products.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('otherproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OtherProducts')),
            ],
            bases=('orders.otherproducts',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('otherproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OtherProducts')),
            ],
            bases=('orders.otherproducts',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('otherproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OtherProducts')),
            ],
            bases=('orders.otherproducts',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('otherproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OtherProducts')),
                ('extra_cheese', models.BooleanField(default=False)),
            ],
            bases=('orders.otherproducts',),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='dinner_platters',
            field=models.ManyToManyField(blank=True, related_name='dinner_platters', to='orders.DinnerPlatter'),
        ),
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(blank=True, related_name='pastas', to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(blank=True, related_name='salads', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subs', to='orders.Sub'),
        ),
    ]
