# Generated by Django 2.1.7 on 2019-04-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190405_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='products.Topping'),
        ),
    ]
