# Generated by Django 2.1.7 on 2019-04-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsWithUniformSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsWithVariousSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_small', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('price_large', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price_small_with_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_small_with_one_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_small_with_two_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_small_with_three_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_large_with_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_large_with_one_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_large_with_two_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_large_with_three_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('itemswithvarioussize_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ItemsWithVariousSize')),
            ],
            bases=('products.itemswithvarioussize',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('itemswithuniformsize_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ItemsWithUniformSize')),
            ],
            bases=('products.itemswithuniformsize',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('itemswithuniformsize_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ItemsWithUniformSize')),
            ],
            bases=('products.itemswithuniformsize',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('itemswithvarioussize_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ItemsWithVariousSize')),
            ],
            bases=('products.itemswithvarioussize',),
        ),
    ]
